--task 1
CREATE TABLE GROUPS (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2,
  C_VAL NUMBER
);

CREATE TABLE STUDENTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2,
    GROUP_ID NUMBER,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID)
);
